name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          openjdk-17-jdk \
          unzip \
          zip \
          git \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          libncurses5 \
          libstdc++6 \
          libffi-dev \
          libssl-dev \
          build-essential \
          pkg-config \
          libsqlite3-dev

        pip install --upgrade pip
        pip install buildozer cython==0.29.36

    - name: Build with Buildozer
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: qrchat-apk
        path: bin/*.apk
