name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3 python3-pip python3-setuptools python3-venv git zip unzip openjdk-17-jdk libncurses6

    - name: Install Android SDK & NDK
      run: |
        mkdir -p $HOME/android
        cd $HOME/android
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip -q cmdline-tools.zip -d cmdline-tools
        yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/android "platforms;android-31" "build-tools;31.0.0" "platform-tools" "ndk;25.1.8937393"
        echo "ANDROIDSDK=$HOME/android" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/android/ndk/25.1.8937393" >> $GITHUB_ENV
        echo "PATH=$HOME/android/platform-tools:$HOME/android/cmdline-tools/cmdline-tools/bin:$PATH" >> $GITHUB_ENV

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython
        pip install buildozer

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-apk
        path: bin/*.apk
